server {
    listen 80;
    server_name localhost;

    # API и админка — идут на Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    # Статика Django (собранная collectstatic)
    location /static/ {
        alias /var/www/static/;
    }

    # Всё остальное — React
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}